spring:
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.mikhailov.otus.task8.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local