spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true